// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolRequestUserMessageContextAction } from "./ToolRequestUserMessageContextAction";
import type { UserInput } from "./UserInput";

/**
 * EXPERIMENTAL. Response payload containing a normal user composer message.
 */
export type ToolRequestUserMessageResponse = { items: Array<UserInput>, contextAction: ToolRequestUserMessageContextAction, };
